-- https://dba.stackexchange.com/questions/284859/sql-shopping-cart-design-for-a-marketplace
--Base de datos sample:  Carrito de compra
--============================================================TABLAS
--medio-pago
CREATE TABLE PAYMENT_METHOD(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

--estados del pago
CREATE TABLE PAYMENT_STATE(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

--estados de la orden
CREATE TABLE ORDER_STATE(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

--roles
CREATE TABLE ROLE(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

--categoria
CREATE TABLE CATEGORY(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
STATE INTEGER
);

--envios
CREATE TABLE SHIPPING(
ID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(255),
DESCRIPTION VARCHAR(255)
);

--tabla de productos
CREATE TABLE PRODUCT (
ID INTEGER PRIMARY KEY NOT NULL ,
ID_CATEGORY INTEGER, --FK
NAME VARCHAR (255),
PRICE DECIMAL(15,2),
STOCK INTEGER,
DISCOUNT INTEGER,
DESCRIPTION VARCHAR (255),
STATE INTEGER,
FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID)
);

--persona
CREATE TABLE PERSON(
RUT INTEGER PRIMARY KEY NOT NULL ,
ID_ROLE INTEGER, --FK
NAME VARCHAR(255),
LASTNAME VARCHAR(255),
DATE_BIRTH DATE,
EMAIL VARCHAR(255),
PHONE INTEGER,
ADDRESS VARCHAR(255),
PASSWORD VARCHAR(255),
STATE INTEGER,
CREATE_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID)
);

--Orden de compra
CREATE TABLE PURCHASE_ORDER (
ID INTEGER PRIMARY KEY NOT NULL ,
RUT INTEGER ,--FK
ID_SHIPPING INTEGER,--FK
ID_ORDER_STATE INTEGER,--FK
DISCOUNT INTEGER,
TOTAL_PRICE DECIMAL(15,2),
CREATE_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
FOREIGN KEY (RUT) REFERENCES PERSON (RUT),
FOREIGN KEY (ID_SHIPPING) REFERENCES SHIPPING (ID),
FOREIGN KEY (ID_ORDER_STATE) REFERENCES ORDER_STATE (ID)
);

--Contenido del carro
CREATE TABLE ORDER_ITEMS(
ID INTEGER PRIMARY KEY NOT NULL ,
ID_PRODUCT INTEGER,--FK
ID_PURCHASE_ORDER INTEGER,--FK
PRICE DECIMAL(15,2),
QUANTITY INTEGER,
CREATE_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID),
FOREIGN KEY (ID_PURCHASE_ORDER) REFERENCES PURCHASE_ORDER (ID)
);

--transaccion
CREATE TABLE TRANSACTION(
ID INTEGER PRIMARY KEY NOT NULL ,
ID_PAYMENT_METHOD INTEGER, --FK
ID_PAYMENT_STATE INTEGER,--FK
ID_PURCHASE_ORDER INTEGER,--FK
CARD_NUMBER INTEGER,
MSG_TRANSACTION VARCHAR (255),
CREATE_AT TIMESTAMP,
MODIFIED_AT TIMESTAMP,
FOREIGN KEY (ID_PAYMENT_METHOD) REFERENCES PAYMENT_METHOD (ID),
FOREIGN KEY (ID_PAYMENT_STATE) REFERENCES PAYMENT_STATE (ID),
FOREIGN KEY (ID_PURCHASE_ORDER) REFERENCES PURCHASE_ORDER (ID)
);

--============================================================ SEQUENCE AUTO_INCREMENT
CREATE SEQUENCE PAYMENT_METHOD_ID_SEC;
ALTER TABLE PAYMENT_METHOD ALTER ID SET DEFAULT NEXTVAL('PAYMENT_METHOD_ID_SEC');

CREATE SEQUENCE PAYMENT_STATE_ID_SEC;
ALTER TABLE PAYMENT_STATE ALTER ID SET DEFAULT NEXTVAL('PAYMENT_STATE_ID_SEC');

CREATE SEQUENCE ORDER_STATE_ID_SEC;
ALTER TABLE ORDER_STATE ALTER ID SET DEFAULT NEXTVAL('ORDER_STATE_ID_SEC');

CREATE SEQUENCE ROLE_ID_SEC;
ALTER TABLE ROLE ALTER ID SET DEFAULT NEXTVAL('ROLE_ID_SEC');

CREATE SEQUENCE CATEGORY_ID_SEC;
ALTER TABLE CATEGORY ALTER ID SET DEFAULT NEXTVAL('CATEGORY_ID_SEC');

CREATE SEQUENCE SHIPPING_ID_SEC;
ALTER TABLE SHIPPING ALTER ID SET DEFAULT NEXTVAL('SHIPPING_ID_SEC');

CREATE SEQUENCE PRODUCT_ID_SEC;
ALTER TABLE PRODUCT ALTER ID SET DEFAULT NEXTVAL('PRODUCT_ID_SEC');

CREATE SEQUENCE PURCHASE_ORDER_ID_SEC;
ALTER TABLE PURCHASE_ORDER ALTER ID SET DEFAULT NEXTVAL('PURCHASE_ORDER_ID_SEC');

CREATE SEQUENCE ORDER_ITEMS_ID_SEC;
ALTER TABLE ORDER_ITEMS ALTER ID SET DEFAULT NEXTVAL('ORDER_ITEMS_ID_SEC');

CREATE SEQUENCE TRANSACTION_ID_SEC;
ALTER TABLE TRANSACTION ALTER ID SET DEFAULT NEXTVAL('TRANSACTION_ID_SEC');

--
-- Sin secuencia:
--     - TABLE PERSON

--============================================================DATOS UNICOS

INSERT INTO PAYMENT_METHOD("name", description)VALUES('Debito', 'Tarjeta de credito nacional');
INSERT INTO PAYMENT_METHOD("name", description)VALUES('Visa', 'Tarjeta de credito internacional');
INSERT INTO PAYMENT_METHOD("name", description)VALUES('MasterCard', 'Tarjeta de credito internacional');

INSERT INTO PAYMENT_STATE("name", description)VALUES('PENDIENTE', 'A la espera');
INSERT INTO PAYMENT_STATE("name", description)VALUES('APROBADO', 'Esta todo bien');
INSERT INTO PAYMENT_STATE("name", description)VALUES('RECHAZADO', 'Por algun problema');

INSERT INTO ORDER_STATE("name", description)VALUES('PENDIENTE', 'A la espera');
INSERT INTO ORDER_STATE("name", description)VALUES('PROCESANDO', 'En curso');
INSERT INTO ORDER_STATE("name", description)VALUES('CONCLUIDA', 'OK');

INSERT INTO SHIPPING("name", description)VALUES('PRESENCIAL', 'Entrega en local');
INSERT INTO SHIPPING("name", description)VALUES('CORREO CHILE', 'Empresa de courier');
INSERT INTO SHIPPING("name", description)VALUES('CHILEXPRESS', 'Empresa de courier');

INSERT INTO ROLE("name", description)VALUES( 'ADMIN', 'Administrador');
INSERT INTO ROLE("name", description)VALUES( 'OPERATOR', 'Operadores del sitio');
INSERT INTO ROLE("name", description)VALUES( 'USER', 'Usuario o cliente');
--==
INSERT INTO CATEGORY ("name", state) VALUES ('Frutas y verduras',1);
INSERT INTO CATEGORY ("name", state) VALUES ('Pastelería',1);
INSERT INTO CATEGORY ("name", state) VALUES ('Carnes y pescados',1);

INSERT INTO PRODUCT (id_category, "name", price, stock, discount, description, state) VALUES(1, 'Guayaba Feijoa' , 300, 500, 0, '', 1);
INSERT INTO PRODUCT (id_category, "name", price, stock, discount, description, state) VALUES(1, 'Mango' , 300, 500, 0, '', 1);
INSERT INTO PRODUCT (id_category, "name", price, stock, discount, description, state) VALUES(1, 'Manzana' , 300, 500, 0, '', 1);
INSERT INTO PRODUCT (id_category, "name", price, stock, discount, description, state) VALUES(1, 'Aguacate' , 2500, 98, 0, '', 1);

--============================================================DATOS PRUEBAS
-- CLIENTES y usuarios
INSERT INTO PERSON
(rut, id_role, "name", lastname, date_birth, email, phone, address, "password", state, create_at, modified_at)
VALUES(15943970, 3, 'Johannes', 'Kepler', TO_TIMESTAMP('28/06/1992','DD/MM/YYYY'), 'kepler@me.com', 15943970, 'direccion ejemplo 1234', '1234', 1, TO_TIMESTAMP('28/06/2022 17:30:00','DD/MM/YYYY HH24:MI:SS'), null);

-- COMPRA
INSERT INTO PURCHASE_ORDER
(rut, id_shipping, id_order_state, discount, total_price, create_at, modified_at)
VALUES(15943970 , 1, 1, 0, 2100, TO_TIMESTAMP('28/06/2022 17:30:00','DD/MM/YYYY HH24:MI:SS'), null);

INSERT INTO ORDER_ITEMS
(id_product, id_purchase_order, price, quantity, create_at, modified_at)
VALUES(1, 1, 600, 2, TO_TIMESTAMP('28/06/2022 17:30:00','DD/MM/YYYY HH24:MI:SS'), null);
INSERT INTO ORDER_ITEMS
(id_product, id_purchase_order, price, quantity, create_at, modified_at)
VALUES(2, 1, 900, 3, TO_TIMESTAMP('28/06/2022 17:30:00','DD/MM/YYYY HH24:MI:SS'), null);
INSERT INTO ORDER_ITEMS
(id_product, id_purchase_order, price, quantity, create_at, modified_at)
VALUES(1, 1, 600, 2, TO_TIMESTAMP('28/06/2022 17:30:00','DD/MM/YYYY HH24:MI:SS'), null);
